<a href="https://colab.research.google.com/github/MdMahmudulHasanRifat/Lab_Report_2/blob/main/222002048_CSE312_222D3_LabReport02_knnFromScratch_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from collections import Counter
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.neighbors import KNeighborsClassifier

def euclidean_distance(x1, x2):
    return np.sqrt(np.sum((x1 - x2) ** 2))

class KNN:
    def __init__(self, k=3):
        self.k = k

    def fit(self, X, y):
        self.X_train = np.array(X)
        self.y_train = np.array(y)

    def predict(self, X):
        return np.array([self._predict(x) for x in X])

    def _predict(self, x):
        distances = [euclidean_distance(x, x_train) for x_train in self.X_train]
        k_indices = np.argsort(distances)[:self.k]
        k_labels = self.y_train[k_indices]
        return Counter(k_labels).most_common(1)[0][0]

def accuracy(y_true, y_pred):
    return np.sum(y_true == y_pred) / len(y_true)

def confusion_matrix(y_true, y_pred):
    classes = np.unique(y_true)
    matrix = np.zeros((len(classes), len(classes)), dtype=int)
    for actual, predicted in zip(y_true, y_pred):
        i = np.where(classes == actual)[0][0]
        j = np.where(classes == predicted)[0][0]
        matrix[i][j] += 1
    return matrix

def precision_recall_f1(y_true, y_pred):
    cm = confusion_matrix(y_true, y_pred)
    TP = np.diag(cm)
    FP = np.sum(cm, axis=0) - TP
    FN = np.sum(cm, axis=1) - TP
    precision = TP / (TP + FP + 1e-9)
    recall = TP / (TP + FN + 1e-9)
    f1 = 2 * (precision * recall) / (precision + recall + 1e-9)
    return {
        "precision": np.mean(precision),
        "recall": np.mean(recall),
        "f1_score": np.mean(f1)
    }

iris = load_iris()
X, y = iris.data, iris.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

model = KNN(k=3)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("🌸 KNN From Scratch Results:")
print("Accuracy:", accuracy(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Metrics:", precision_recall_f1(y_test, y_pred))

sk_model = KNeighborsClassifier(n_neighbors=3)
sk_model.fit(X_train, y_train)
y_sk = sk_model.predict(X_test)

print("\n🤖 Scikit-learn KNN Results:")
print(classification_report(y_test, y_sk))

🌸 KNN From Scratch Results:
Accuracy: 1.0
Confusion Matrix:
 [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
Metrics: {'precision': np.float64(0.9999999999311742), 'recall': np.float64(0.9999999999311742), 'f1_score': np.float64(0.9999999994311741)}

🤖 Scikit-learn KNN Results:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

